name: Rust

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets -- -D clippy::all

  build_and_release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: check
    name: Build and Release
    runs-on: macOS-latest
    strategy:
      matrix:
        mode:
          - name: sram
            cargo_params: ""
            filename: sram
          - name: f64
            cargo_params: --no-default-features --features=flash64
            filename: flash64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: setup
        run: |
          cargo install agb-gbafix

      - name: build
        run: cargo build --release ${{ matrix.mode.cargo_params}}

      - name: build gba
        run: agb-gbafix target/thumbv4t-none-eabi/release/nonogram_advance -o nonogram_advance_v0.9.4_${{ matrix.mode.filename}}.gba -tNonogramAdv -cNGA1 -mEB -r94

      - uses: softprops/action-gh-release@v1
        with:
          files: nonogram_advance_v0.9.4_${{ matrix.mode.filename}}.gba
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}